import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Box from '../components/Box';
import Text from '../components/Text';
import Button from '../components/Button';
import { useState } from 'react';
import { CustomizedModal } from '../components/CustomizedModal';
import { RegistryModalContent } from '../components/RegistryModalContent';
import Title from '../components/Title';
import Step from '../components/Step';

const About: NextPage = () => {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [confirmLoading, setConfirmLoading] = useState(false);
  const [modalText, setModalText] = useState('Content of the modal');
  const showModal = () => {
    setIsModalOpen(true);
  };
  const handleOk = () => {
    setModalText('The modal will be closed after two seconds');
    setConfirmLoading(true);
    setTimeout(() => {
      setIsModalOpen(false);
      setConfirmLoading(false);
    }, 2000);
  };
  const handleCancel = () => {
    console.log('Clicked cancel button');
    setIsModalOpen(false);
  };

  return (
    <div className='h-full'>

      <Head>
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://use.typekit.net/eao3xkl.css" />
        <title>Todo Bubki</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <header>
        about
      </header>
    </div>
  );
};

export default About;
