import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Box from '../components/Box';
import { navData } from '../src/data.config';

const Home: NextPage = () => (
  <div>
    <Head>
      <link rel="icon" href="/favicon.ico" />
      <link rel="stylesheet" href="https://use.typekit.net/eao3xkl.css" />
      <title>Todo Bubki</title>
      <meta name="description" content="Generated by create next app" />
    </Head>

    <main>
      <h1>
        <Box>
          <div className='flex w-full justify-between'>
            <div className='text-3xl font-bold flex'>Logo</div>
            <nav className='flex font-base'>
              {navData.map(item => (
                <div
                  key={item.id}
                  className='ml-3'
                >
                  {item.title}
                </div>
              ))}
              <div>Rus</div>
              <div>Личный кабинет</div>
            </nav>
          </div>
        </Box>
      </h1>

      <p className=''>
          Get started by editing{' '}
        <code className=''>pages/index.tsx</code>
      </p>
    </main>

    <footer className=''>
      <a
        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
        target="_blank"
        rel="noopener noreferrer"
      >
          Powered by{' '}
        <span className=''>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
      </a>
    </footer>
  </div>
);

export default Home;
