import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Box from '../components/Box';
import Text from '../components/Text';
import Button from '../components/Button';
import { useState } from 'react';
import { Modal } from 'antd';

const Home: NextPage = () => {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [confirmLoading, setConfirmLoading] = useState(false);
  const [modalText, setModalText] = useState('Content of the modal');
  const showModal = () => {
    setIsModalOpen(true);
  };
  const handleOk = () => {
    setModalText('The modal will be closed after two seconds');
    setConfirmLoading(true);
    setTimeout(() => {
      setIsModalOpen(false);
      setConfirmLoading(false);
    }, 2000);
  };
  const handleCancel = () => {
    console.log('Clicked cancel button');
    setIsModalOpen(false);
  };

  return (
    <div>
      {isModalOpen && (<Modal
        title="Title"
        open={isModalOpen}
        onOk={handleOk}
        confirmLoading={confirmLoading}
        onCancel={handleCancel}
      >
        <p>{modalText}</p>
      </Modal>)}
      <Head>
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://use.typekit.net/eao3xkl.css" />
        <title>Todo Bubki</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1>
          <Box>
            <div className='flex w-full justify-between py-5 items-center border'>
              <div className='text-3xl font-bold flex'>Logo</div>
              <nav className='flex font-base font-medium text-lg items-center'>
                <div className='px-6 py-2'>
                  <a href='/about' className='text-center text-base font-medium hover:text-highlight'><Text tid={'about'} /></a>
                </div>
                <div className='px-6 py-2'>
                  <a href='/univers-list' className='text-center text-base hover:text-highlight'><Text tid={'universityList'} /></a>
                </div>
                <div className='px-6 py-2'>
                  <a href='/contacts' className='text-center text-base hover:text-highlight'><Text tid={'contacts'} /></a>
                </div>
                <div className='text-center px-6 py-2 hover:text-highlight'>Rus</div>
                <Button onClick={showModal}>
                  <Text tid={'profile'} />
                </Button>
              </nav>
            </div>
          </Box>
        </h1>

        <p className=''>
          Get started by editing{' '}
          <code className=''>pages/index.tsx</code>
        </p>
      </main>

      <footer className=''>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className=''>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );};

export default Home;
