import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Box from '../components/Box';
import Text from '../components/Text';

const Home: NextPage = () => (
  <div>
    <Head>
      <link rel="icon" href="/favicon.ico" />
      <link rel="stylesheet" href="https://use.typekit.net/eao3xkl.css" />
      <title>Todo Bubki</title>
      <meta name="description" content="Generated by create next app" />
    </Head>

    <main>
      <h1>
        <Box>
          <div className='flex w-full justify-between'>
            <div className='text-3xl font-bold flex'>Logo</div>
            <nav className='flex font-base font-medium text-lg'>
              <a href='/about' className='text-center font-medium px-6 py-2 hover:text-highlight'><Text tid={'about'} /></a>
              <a href='/univers-list' className='text-center px-6 py-2 hover:text-highlight'><Text tid={'universityList'} /></a>
              <a href='/contacts' className='text-center px-6 py-2 hover:text-highlight'><Text tid={'contacts'} /></a>
              <div className='text-center px-6 py-2 hover:text-highlight'>Rus</div>
              <div className='text-center px-6 py-2 hover:text-highlight'><Text tid={'profile'} /></div>
            </nav>
          </div>
        </Box>
      </h1>

      <p className=''>
          Get started by editing{' '}
        <code className=''>pages/index.tsx</code>
      </p>
    </main>

    <footer className=''>
      <a
        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
        target="_blank"
        rel="noopener noreferrer"
      >
          Powered by{' '}
        <span className=''>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
      </a>
    </footer>
  </div>
);

export default Home;
